
default_config:
tts:
  - platform: voicerss
    api_key: 6cb2e173ab16465ea656d538c3547fd8

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

discovery:

light:
  - platform: nanoleaf
    host: [REDACTED]
    token: [REDACTED]
  - platform: group
    name: Boudoir Ceiling Light
    entities:
      - light.ceiling_1
      - light.ceiling_2
  - platform: switch
    name: Vine Lights
    entity_id: switch.vine_lights
  - platform: switch
    name: Kitchen Cabinet Lighting
    entity_id: switch.cabinet_lighting

aarlo:
  username: [REDACTED]
  password: !secret aarlo
  
alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: disarmed
    trigger_time: 30
    alarm_volume: 8
    code: !secret aarlo_code
    code_arm_required: false

sensor:
  - platform: aarlo
    monitored_conditions:
      - battery_level
      - signal_strength
  - platform: time_date
    display_options:
      - "date"
      - "time"
  - platform: template
    sensors:
      timenew:
        friendly_name: "XTime"
        value_template: >
          {% set time = states('sensor.time') %}
          {% set hour = time[:2]|int %}
          {{ '{:02d}:{} {}'.format(hour if hour == 12 else hour % 12, time[3:5], 'PM' if hour>11 else 'AM') }}
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: processor_temperature
      - type: processor_use
      - type: last_boot   
  - platform: template
    sensors:
      washer_state:
        friendly_name: 'Washer State'
        value_template: '{{ state_attr("sensor.washer", "run_state") }}'
        icon_template: mdi:washing-machine      
      washer_program_length:
        friendly_name: 'Washer Program Length'
        value_template: >-
          {% set washerprogramminutes = (states.sensor.washer.attributes.initial_time.split(':')[0]|int * 60) + (states.sensor.washer.attributes.initial_time.split(':')[1] | int) %}
          {{ washerprogramminutes }}
        icon_template: mdi:washing-machine      
      washer_remaining_time:
        friendly_name: 'Washer Remaining Time'
        value_template: >-
          {% set washerremainminutes = (states.sensor.washer.attributes.remain_time.split(':')[0]|int * 60) + (states.sensor.washer.attributes.remain_time.split(':')[1] | int) %}
          {{ washerremainminutes }}
        icon_template: mdi:washing-machine
      washer_progress:
        friendly_name: 'Washer Progress'
        value_template: >-
          {% if (states.sensor.washer_program_length.state | int) < 1 %}
            0
          {% else %}          
            {% set washerprogress = (100 - (((states.sensor.washer_remaining_time.state | int) / (states.sensor.washer_program_length.state | int)) * 100)) %}
            {{ washerprogress }}
          {% endif %}             
        icon_template: mdi:washing-machine
        
      dryer_state:
        friendly_name: 'Dryer State'
        value_template: '{{ state_attr("sensor.dryer", "run_state") }}'
        icon_template: mdi:tumble-dryer     
      dryer_program_length:
        friendly_name: 'Dryer Program Length'
        value_template: >-
          {% set dryerprogramminutes = (states.sensor.dryer.attributes.initial_time.split(':')[0]|int * 60) + (states.sensor.dryer.attributes.initial_time.split(':')[1] | int) %}
          {{ dryerprogramminutes }} 
        icon_template: mdi:tumble-dryer     
      dryer_remaining_time:
        friendly_name: 'Dryer Remaining Time'
        value_template: >-
          {% set dryerprogramminutes = (states.sensor.dryer.attributes.remain_time.split(':')[0]|int * 60) + (states.sensor.dryer.attributes.remain_time.split(':')[1] | int) %}
          {{ dryerprogramminutes }}
        icon_template: mdi:tumble-dryer
      dryer_progress:
        friendly_name: 'Dryer Progress'
        value_template: >-
          {% if (states.sensor.dryer_program_length.state | int) < 1 %}
            0
          {% else %}           
            {% set dryerprogress = (100 - (((states.sensor.dryer_remaining_time.state | int) / (states.sensor.dryer_program_length.state | int)) * 100)) %}
            {{ dryerprogress }}
          {% endif %}           
        icon_template: mdi:tumble-dryer   
  
media_player:
  - platform: androidtv
    name: B-Chromecast
    host: [REDACTED]
    apps:
      com.spotify.tv.android: "Spotify"
      com.netflix.ninja: "Netflix"
      com.hulu.livingroomplus: "Hulu"
      com.hbo.hbonow: "HBO"
  - platform: universal
    name: Boudoir TV
    children:
      - media_player.boudoir_tv
      - media_player.b_chromecast
      - media_player.boudoir_samsung_tv
    commands:
      turn_on:
        service: media_player.turn_off
        data:
          entity_id: media_player.b_chromecast
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.b_chromecast
      volume_up:
        service: media_player.volume_up
        data:
          entity_id: media_player.boudoir_samsung_tv
      volume_down:
        service: media_player.volume_down
        data:
          entity_id: media_player.boudoir_samsung_tv
      volume_mute:
        service: media_player.volume_mute
        data:
          entity_id: media_player.boudoir_samsung_tv
    attributes:
      is_volume_muted: media_player.boudoir_samsung_tv|volume_level
      state: media_player.b_chromecast
      source: media_player.boudoir_tv
    device_class: tv


group:
  bedroom:
    name: BedroomLights
    entities:
      - light.bedside_lamp
      - switch.vine_lights
      - light.bedroom_floor_lamp
  boudoir:
    name: BoudoirLights
    entities:
      - light.nanoleaf
      - light.desk_lamp
      - light.standing_lamp
      - light.ceiling_1
      - light.ceiling_2
      - light.hue_play_gradient_lightstrip_1
  office:
    name: OfficeLights
    entities:
      - light.office_strip
      - light.desk_lamp_2
      - light.office_desk_lamp_1
  kitchen:
    name: KitchenLights
    entities:
      - light.hue_white_lamp_1
      - light.hue_white_lamp_2
      - light.hue_white_lamp_3
      - light.hue_white_lamp_4
      - light.kitchen_5
      - light.kitchen_6
  livingroom:
    name: LivingRoomLights
    entities:
      - light.living_room_ceiling_light_1
      - light.living_room_ceiling_light_2
      - light.living_room_couch_lamp
      - light.hall_lamp

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: aarlo
    ffmpeg_arguments: "-pred 1 -q:v 2"
mqtt:
  discovery: true
